Feat #44 PopupMenu 제작
pie-sfac/3-20-gangstarr pull request #53
Opened 2023-07-31 10:12 UTC by sungin46

## 사용 방법

App.tsx에 아래와 같이 예시코드 작성

`
// 메뉴명 배열 선언
const menuName = [
  { id: 1, menu: '메뉴1' },
  { id: 2, menu: '메뉴2' },
  { id: 3, menu: '메뉴3' },
]

// 초기값은 false
const [isVisible, setIsVisible] = useState(false);

// onClick 함수 선언
const handlePopup = () => {
  return setIsVisible(!isVisible);
}

return (
  <PoinTStyleProvider>
      <Button onClick={handlePopup}>팝업 토글</Button>
     // menuLists로 메뉴명 받아오고 isHide로 팝업 토글
      <PopupMenu menuLists={menuName} isHide={isVisible}></PopupMenu>
  </PoinTStyleProvider>
)
`

2023-07-31 10:15 UTC, jennie-0530 commented
굿입니다

2023-08-01 01:59 UTC, 0SCAR0421 commented
예시를 보니 Popup을 여는 것도 버튼을 통해서 진행되고 닫는것도 버튼을 눌러야 진행되는거 같은데 맞나요?

일반적이라면 외부를 클릭해서 닫지않나 라는 생각을 해봅니다

2023-08-01 02:01 UTC, 0SCAR0421 requested changes

2023-08-01 02:01 UTC, 0SCAR0421 commented on src/components/popupmenu/PopupMenuComponents.ts
> +`;
enter please 🙏

2023-08-01 02:01 UTC, 0SCAR0421 commented on src/components/popupmenu/PopupMenuComponents.ts
파일명 통일 부탁드려요 🙏

2023-08-01 02:01 UTC, 0SCAR0421 commented on src/components/popupmenu/index.ts
저희 export 하는 방법 다시 확인부탁드려요 🙏

2023-08-01 02:01 UTC, 0SCAR0421 commented on src/components/popupmenu/PopupMenuComponents.ts
> +`;
다른 컴포넌트에서도 완벽히 똑같은 코드를 사용하는걸로 아는데 통합하는게 맞지않나요? 🙏

2023-08-01 02:01 UTC, 0SCAR0421 commented on src/components/popupmenu/PopupMenu.tsx
onClick evnet는 누가 달아주죠?

PopupMenu가 단순히 정보를 제공하는 텍스트인가요? 클릭했을때 이벤트는 없나요? 🙏

2023-08-01 02:17 UTC, sungin46 commented on src/components/popupmenu/PopupMenuComponents.ts
> +`;
확인했습니다 🙏

2023-08-01 02:18 UTC, sungin46 commented on src/components/popupmenu/index.ts
확인했습니다 🙏

2023-08-01 02:33 UTC, sungin46 commented on src/components/popupmenu/PopupMenuComponents.ts
> +`;
style 폴더에 keyframe.ts 파일 하나 파서 올리겠습니다 🙏

2023-08-01 05:11 UTC, sungin46 commented on src/components/popupmenu/PopupMenu.tsx
배열에 링크까지 같이 달도록 interface 수정했습니다 🙏

2023-08-02 08:48 UTC, sungin46 commented
상기 수정사항 반영되었습니다. 확인 부탁드립니다 🙏

2023-08-03 01:36 UTC, 0SCAR0421 commented
코드 확인해보니 index.ts export와 팝업을 누른뒤 링크가 변경되고 다시 눌렀을 때 한번에 안나오는 버그가 있네요 확인 부탁드립니다 🙏

2023-08-03 02:09 UTC, merged