Feat #52 AppBar 제작
pie-sfac/3-20-gangstarr pull request #54
Opened 2023-08-01 07:25 UTC by dong-fa

뒤로가기 버튼 history.go(-1) 사용해서 구현
페이지 타이틀은 props로 전달
아이콘 개수별, 텍스트 버튼별 컴포넌트 개별 생성

컴포넌트 이름 재정의 필요한지 의견 필요

사용예시
`return (
      <AppBarNomal title={'페이지 타이틀'}></AppBarNomal>
  ); `

2023-08-01 07:27 UTC, jennie-0530 commented on src/components/appbar/AppBarCount.tsx
> +const AppBarContainer = styled.div`
styled component 변수들은 하단이 아니라 상단에 모아두는 것이 어떨까요?

2023-08-01 07:29 UTC, jennie-0530 commented on src/components/appbar/AppBarCount.tsx
> +const GobackButton = styled.button`
카멜 케이스를 사용해서 GoBackButton으로 수정하는 것은 어떠실까요?!

2023-08-01 07:32 UTC, sungin46 commented on src/components/appbar/AppBarCount.tsx
> +`;
반복되는 컴포넌트들이 많은데 한번에 묶어서 쓰면 좋을거같아요 🙏

2023-08-01 07:55 UTC, dong-fa commented on src/components/appbar/AppBarCount.tsx
> +const AppBarContainer = styled.div`
그러고보니 저만 아래에 작성하고 있었네요 수정 하겠읍니다.

2023-08-01 12:36 UTC, 0SCAR0421 requested changes
- 모든 컴포넌트의 onClickAction 함수의 의도가 불명확함. 
사용자가 원하는 함수를 동작시키기 위해서는 추가적인 작업이 필요할것으로 보임.
- history.go 함수는 페이지 새로고침이 발생하는 것이 아닌지 확인 필요.
- 단순 오타 수정

2023-08-01 12:36 UTC, 0SCAR0421 commented on src/components/appbar/AppBarCount.tsx
> +          history.go(-1);
history 객체의 함수는 실행시 page refresh가 발생하지 않나요?

2023-08-01 12:36 UTC, 0SCAR0421 commented on src/components/appbar/AppBarNomal.tsx
Nomal -> Normal 
오타인거 같습니다

2023-08-01 12:36 UTC, 0SCAR0421 commented on src/components/appbar/AppBarNomal.tsx
> +const AppBarNomal = ({ title }: IappBarProps): JSX.Element => {
여기도 오타인거 같습니다

2023-08-01 12:36 UTC, 0SCAR0421 commented on src/components/appbar/AppBarTextOne.tsx
> +  };
정확히 무슨 동작을 하는 함수인지 의도가 불명확한거 같습니다

2023-08-01 12:36 UTC, 0SCAR0421 commented on src/components/appbar/AppBarTextOne.tsx
> +        </ActionBtn1>
이 버튼을 클릭했을 때 onClickAction1이 실행되는 건 알겠는데 위에서도 언급했듯이 사용자가 원하는 동작은 일어나지 못하는거 같습니다 확인해주세요

2023-08-01 13:00 UTC, dong-fa commented on src/components/appbar/AppBarCount.tsx
> +          history.go(-1);
history.pushstate()를 쓰면 리프레시 없이 페이지 이동을 할 수 있는걸로 알고 있습니다. 
이거 이용해서 페이지 이동하는걸 찾아봐야겠네요.
추가로 혹시나 있을 브라우저 뒤로가기 버튼을 막는것도 고려해봐야 될 것 같기도 하네요.

2023-08-01 13:00 UTC, dong-fa commented on src/components/appbar/AppBarNomal.tsx
확인

2023-08-01 13:00 UTC, dong-fa commented on src/components/appbar/AppBarNomal.tsx
> +const AppBarNomal = ({ title }: IappBarProps): JSX.Element => {
확인

2023-08-04 01:39 UTC, 0SCAR0421 requested changes

2023-08-04 01:39 UTC, 0SCAR0421 commented on src/components/appbar/index.ts
> +export * from './AppBar';
export {default as AppBar} from './AppBar' 형식이어야 하는거 같습니다

2023-08-04 01:39 UTC, 0SCAR0421 commented on src/components/appbar/AppBar.tsx
> +          history.go(-1);
리프레쉬 이슈 반영안된거 같습니다 확인해주세요

2023-08-04 01:39 UTC, 0SCAR0421 commented on src/components/appbar/AppBar.tsx
> +              <Graphic name={`${iconItem.iconName}`} />
상당수의 아이콘이 AppBar의 영역보다 크게 나옵니다 확인해주세요

2023-08-04 02:10 UTC, sungin46 reviewed
죠습니다 👍

2023-08-04 02:23 UTC, dong-fa commented on src/components/appbar/index.ts
> +export * from './AppBar';
확인

2023-08-04 02:25 UTC, jennie-0530 commented on src/components/appbar/AppBar.tsx
> +const IconBtn = styled.button`
저희 변수명은 줄이지 않고 쓰기로 했어요! IconButton으로 수정 부탁드려요~! 다른 Btn도 수정 부탁드립니다!

2023-08-04 02:26 UTC, dong-fa commented on src/components/appbar/AppBar.tsx
> +          history.go(-1);
페이지 이동이 어떻게 되었느냐에 따라 리프레시가 작동 여부 확인 되었습니다.
일반 html 페이지 이동처럼 새로운 페이지를 이동한다면 popstate이벤트가 발생하게 되면서  history.go(-1)작동시 리프레시가 발생하는걸로 확인되었습니다.
하지만 popstate이벤트 없이 라우트 이동을 한다면 history.go(-1)가 작동해도 리프레시 없이 작동하는걸 확인했습다.

2023-08-04 02:27 UTC, dong-fa commented on src/components/appbar/AppBar.tsx
> +              <Graphic name={`${iconItem.iconName}`} />
확인 피그마 다시 확인하고 수정하겠습니다.

2023-08-04 02:27 UTC, dong-fa commented on src/components/appbar/AppBar.tsx
> +const IconBtn = styled.button`
확인

2023-08-04 06:59 UTC, jennie-0530 commented
고생하셨읍니다

2023-08-04 07:07 UTC, sungin46 commented
is 빠킹 Good 👍

2023-08-04 07:56 UTC, sungin46 reviewed
is 바뀐 Good 👍

2023-08-04 09:08 UTC, merged